PRODUCT_COPY_FILES += \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
	vendor/fairphone/fp1/proprietary/system/lib/libion.so:system/lib/libion.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
	vendor/fairphone/fp1/proprietary/system/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
	vendor/fairphone/fp1/proprietary/system/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
	vendor/fairphone/fp1/proprietary/system/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
	vendor/fairphone/fp1/proprietary/system/lib/libnvram.so:system/lib/libnvram.so \
	vendor/fairphone/fp1/proprietary/system/lib/libfile_op.so:system/lib/libfile_op.so \
	vendor/fairphone/fp1/proprietary/system/lib/libhwm.so:system/lib/libhwm.so \
	vendor/fairphone/fp1/proprietary/system/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
	vendor/fairphone/fp1/proprietary/system/bin/nvram_daemon:system/bin/nvram_daemon \
	vendor/fairphone/fp1/proprietary/system/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	vendor/fairphone/fp1/proprietary/system/bin/memsicd3416x:system/bin/memsicd3416x \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
	vendor/fairphone/fp1/proprietary/system/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
	vendor/fairphone/fp1/proprietary/system/bin/6620_launcher:system/bin/6620_launcher \
	vendor/fairphone/fp1/proprietary/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
	vendor/fairphone/fp1/proprietary/system/xbin/mnld:system/xbin/mnld \
	vendor/fairphone/fp1/proprietary/system/xbin/libmnlp_mt6628:system/xbin/libmnlp_mt6628
